AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Env:
    Type: String
    Default: "dev"

  RawBucketName:
    Type: String
    Default: "eco-fire-watch-raw-v2"

  TrustedBucketName:
    Type: String
    Default: "eco-fire-watch-trusted-v2"

  ClientDatabaseName:
    Type: String
    Default: efwClientDatabase

  ClientBaseName:
    Type: String
    Default: "eco-fire-watch-client"

  ClientUser:
    Type: String
    Default: efwUserDatabase

  ClientPassword:
    Type: String
    Default: grupoEfw2025

Resources:
  EcoFireWatchRaw:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref RawBucketName
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Ref RawBucketName
        - Key: Environment
          Value: !Ref Env

  EcoFireWatchTrusted:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TrustedBucketName
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Ref TrustedBucketName
        - Key: Environment
          Value: !Ref Env


  EcoFireWatchClientSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: EcoFireWatchClientSubnetGroup
      DBSubnetGroupDescription: Database SubnetGroups
      SubnetIds:
        - subnet-02b4ccc0091b49659
        - subnet-066f229cd3694f37c

  EcoFireWatchClient:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - EcoFireWatchClientSubnetGroup
    Properties:
      DBInstanceIdentifier: !Ref ClientBaseName  
      AllocatedStorage: 5
      DBInstanceClass: 'db.t3.micro'
      Engine: postgres
      EngineVersion: '17.6'
      MasterUsername: !Ref ClientUser
      MasterUserPassword: !Ref ClientPassword
      DBSubnetGroupName: !Ref EcoFireWatchClientSubnetGroup
      DBName: !Ref ClientDatabaseName
      VPCSecurityGroups:
        - sg-05adf7622ff81ce36
      PubliclyAccessible: false
      MultiAZ: false
      StorageType: gp2

# aws cloudformation deploy --template-file DataLake.yaml --stack-name eco-fire-watch-datalake