AWSTemplateFormatVersion: 2010-09-09
Description: EcoFireWatch IoT Entrypoint

Resources:
  IotApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: 'efw-iot-entrypoint-api'
      Description: "API Gateway for EcoFireWatch IoT"
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: Name
          Value: EfwIotApi
  
  IotApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt IotApiGateway.RootResourceId
      PathPart: "iot"
      RestApiId: !Ref IotApiGateway

  IotApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref IotApiResource
      RestApiId: !Ref IotApiGateway
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
            - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
            - LambdaArn: !Sub 'arn:aws:lambda:us-east-1:${AWS::AccountId}:function:iot-transaction-trigger'

  IotApiDeploy:
    Type: AWS::ApiGateway::Deployment
    DependsOn: 
      - IotApiGateway
      - IotApiMethod
    Properties:
      RestApiId: !Ref IotApiGateway

  IotApiV1Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: v1
      Description: Iot Data Entrypoint
      RestApiId: !Ref IotApiGateway
      DeploymentId: !Ref IotApiDeploy 
      Variables:
        Environment: Production
      MethodSettings:
        - HttpMethod: "*"
          ResourcePath: "/*" 
          MetricsEnabled: false
          DataTraceEnabled: false