AWSTemplateFormatVersion: 2010-09-09

Resources:
  ExternalDataTrigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: external-data-trigger
      Description: "Lambda function to process external data ingestion"
      Handler: bundle.handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Runtime: nodejs22.x
      Timeout: 300
      MemorySize: 512
      Code:
        S3Bucket: eco-fire-watch-raw-v2
        S3Key: resources/external-data-trigger.zip
      Environment:
        Variables:
          RAW_BUCKET_NAME: eco-fire-watch-raw-v2

  InpeDataSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      FlexibleTimeWindow: 
        Mode: "OFF"
      Name: InpeDataSchedule
      ScheduleExpression: rate(6 hours)
      ScheduleExpressionTimezone: America/Sao_Paulo
      Target: 
        Arn: !GetAtt ExternalDataTrigger.Arn
        Input: !Sub '{ "type":"INPE" }'
        RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
    
  InmetDataSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      FlexibleTimeWindow: 
        Mode: "OFF"
      Name: InmetDataSchedule
      ScheduleExpression: cron(0 0 1 * ? *)
      ScheduleExpressionTimezone: America/Sao_Paulo
      Target: 
        Arn: !GetAtt ExternalDataTrigger.Arn
        Input: !Sub '{ "type":"INMET" }'
        RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole

  DataTreatmentTrigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: data-treatment-trigger
      Description: "Lambda function to process data treatment"
      Handler: src/bundle.handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Runtime: nodejs22.x
      Timeout: 300
      MemorySize: 512
      Code:
        S3Bucket: eco-fire-watch-raw-v2
        S3Key: resources/data-treatment-trigger.zip
      Environment:
        Variables:
          RAW_NAME: eco-fire-watch-raw-v2
          TRUSTED_NAME: eco-fire-watch-trusted-v2
          RDS_HOST: host
          RDS_PORT: 5432
          RDS_DB_NAME: efwClientDatabase
          RDS_USER: efwUserDatabase
          RDS_PASSWORD: password

  IotTransactionTrigger:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: iot-transaction-trigger
      Description: "Lambda function to process IoT transactions"
      Handler: bundle.handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Runtime: nodejs22.x
      Timeout: 300
      MemorySize: 512
      Code:
        S3Bucket: eco-fire-watch-raw-v2
        S3Key: resources/iot-transaction-trigger.zip
      Environment:
        Variables:
          REDIS_KEY: iot-internal-queue
          # Replace in AWS console with actual Redis URL
          REDIS_URL: TODO 
          REDIS_TIME_LIMIT: 600
          REDIS_MAX_QUEUE_SIZE: 10
          S3_BUCKET_NAME: eco-fire-watch-raw-v2
          S3_REGION: us-east-1